### ISSUE TITLE
A cross-platform future?

### ISSUE THREAD

**Issue by DJuego** [CJLove/sockets-cpp#1]
Thank you very much in this project. 

It is promising and fulfills several of my wishes (elegant, modern, header-only,...). Unfortunately an essential requirement for me is that it should be cross-platform (Unix/Linux, Microsoft Windows, macOS,...) Do you consider introducing such a feature in the future  (if it is feasible to do so)?

Again, thank you very much for this contribution! :-)

DJuego

**Comment by CJLove** [comment]
Thanks for the feedback! I do have Windows support planned as a possibility and should be able to add that and test it locally in the near future. I don't have the means to develop/test on macOS, though I'd expect the code to generally build and run there.

**Comment by CJLove** [comment]
Initial Windows support has now been added. I still need to setup Travis-CI, which may enable me to build/test for macOS.

**Comment by CJLove** [comment]
Closing this for now as I've now tested the Windows support locally against Linux and have verified that the code builds and unit tests pass on macOS. Github actions now do Windows and macOS builds.
